### ISSUE TITLE
Provide config

### ISSUE THREAD

**Issue by OvermindDL1** [light2yellow/csgo-csmd#2]
The `CSGO_HOME_DIR` variable is hardcoded to the user's home directory, where it may not be if we, for example, install super-large games onto a more stable and larger disc drive instead of a tiny SSD.  At the very least documenting to change that variable to the installation path is better, though having it read configuration data from somewhere (say in `$HOME/.config/csgo-csmd.config` or so) if it exists would be best so no edits of the script are necessary.

**Comment by light2yellow** [comment]
That's exactly what `--csgo-path` parameter is for. Although config is a good idea for others to be able to launch the script without any aliases.
