### ISSUE TITLE
Usage unclear

### ISSUE THREAD

**Issue by ckarrie** [light2yellow/csgo-csmd#3]
Hi, 

first thanks for the script!

I stuck at the part, where I have to reconnect to community server with `retry`, this can't work because I always stuck on "Initializing World" trying to downloading files and need to kill CSGO in this case. So there is no "previous" connection to any server.

What I do:
- Start CS:GO
- Opened Console and entered `condump` and then `connect ServerIP:Port`
- Opened Shell and run `csgo-csmd --csgo-path ".steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/"`

**Comment by ckarrie** [comment]
Alternate solution:

- Start CS:GO with start parameter `-condebug`
- Connect to the community server
- Kill CS:GO
- Look for `console.log` in your Shell
- Find the base URL
- Find lines beginning with `Discarding queued download of`
- Download manually with wget, don't forget to keep structure of directory

**Comment by light2yellow** [comment]
> I stuck at the part, where I have to reconnect to community server with retry, this can't work because I always stuck on "Initializing World" trying to downloading files and need to kill CSGO in this case.

Firstly, `retry` is an alias for the last `connect foo`.
Secondly, you can open the console by pressing tilde (even at "Initializing world" screen) and that's exactly what README tries to tell at the second step of "Usage", and that's what you will have to do in order to use `csgo-csmd`. Steps 3-7 assume you are able to open the console. Then, by default, `csgo-csmd` finds the latest `condumpXXX.txt` and consumes it.

**Comment by ckarrie** [comment]
> Firstly, retry is an alias for the last connect foo.

Ah, yes...

> Secondly, you can open the console by pressing tilde (even at "Initializing world" screen) and that's exactly what README tries to tell at the second step of "Usage", and that's what you will have to do in order to use csgo-csmd.

No, exactly that doesn't work for me. 

> And that's exactly the reason why this script exists - to omit manual wgetting.

That's a hint for users having the same problems.

**Comment by light2yellow** [comment]
> No, exactly that doesn't work for me.

So, you cannot open a console?

**Comment by ckarrie** [comment]
No, not at the "Initializing world" screen

**Comment by light2yellow** [comment]
If you cannot open the console at the "initializing world", then it has nothing to do with the script. Report an issue to Valve.
