### ISSUE TITLE
--csgo-path: Path does not exist?

### ISSUE THREAD

**Issue by kdmjr94** [light2yellow/csgo-csmd#4]
So I am attempting to use the script you've created and I can't seem to figure out why this issue is occurring...  I'm really new to Linux (installed and have been using for only a day or so) so I may not be doing things correctly, but I have been following your instructions, and maybe I'm just too dense to actually do it correctly.

I run this in the terminal:

`csgo-csmd --csgo-path ~/Games/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/csgo/
`

Now this is where my CSGO is, and I have also done this command using the /home directory for CSGO and it comes up with the same output of:

csgo-csmd: error: argument --csgo-path: Path does not exist.

I'm sorry in advance if this is something super simple to fix and it's just user error, but I would really like to see if I can get this running as it would make for downloading Workshop maps and such so much easier.  If there is anything else that I need to provide to you, please let me know so I can help you to help me!

Thanks!

**Comment by light2yellow** [comment]
That's because you cannot use spaces in paths in the shell - they are special characters that must be escaped. So, instead, try this:
```
csgo-csmd --csgo-path ~/Games/SteamLibrary/steamapps/common/Counter-Strike\ Global\ Offensive/csgo
```

**Comment by kdmjr94** [comment]
Everything seemed to work flawlessly after using the fix that you provided!  Thank you very much and I appreciate the timely reply!
