### ISSUE TITLE
Path does not exist.

### ISSUE THREAD

**Issue by Neutralgger** [light2yellow/csgo-csmd#6]
Hey, i have a problem with the script, it seems that it can't find the path of "argparse.ArgumentTypeError: Path does not exist."
this is the terminal output when running "csgo-csmd"

```
CS:GO Community Server Materials Downloader v0.2.0

Traceback (most recent call last):
  File "/usr/local/bin/csgo-csmd", line 280, in <module>
    csmd.parse_args(CSMD.setup_args().parse_args())
  File "/usr/local/bin/csgo-csmd", line 163, in parse_args
    VerifyCLASyntax.path(self.csgo_path)
  File "/usr/local/bin/csgo-csmd", line 59, in path
    .format(ANSIColors.red, ANSIColors.end))
argparse.ArgumentTypeError: Path does not exist
```

**Comment by light2yellow** [comment]
Well, if path doesn't exist, the path doesn't exist :)
As per README, the default path is `/home/$USER/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo`, which you can alter with a config under `~/.config/csmd/csmd.conf` or with a `--csgo-path <path>` argument. If CS:GO is installed elsewhere, you have to use one of these.
